version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "8081:8080"
      - "9010:9010"  # JMX port for VisualVM
      - "9011:9011"  # RMI port for JMX
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db
    restart: always
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    restart: always
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
    ports:
      - "8083:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    networks:
      - mynetwork

volumes:
  db-data:
  pgadmin-data:

networks:
  mynetwork:
    driver: bridge

