version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: mydatabase
      DB_USER: postgres
      DB_PASSWORD: secret
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: ["start-dev"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "8081:8080"
      - "9010:9010"  # JMX port for VisualVM
      - "9011:9011"  # RMI port for JMX
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db
      - keycloak
    restart: always
    networks:
      - mynetwork
    volumes:
      - ./backend/keycloak_users.csv:/workspace/app/keycloak_users.csv

  frontend:
    build: ./frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    restart: always
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
    ports:
      - "8083:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    networks:
      - mynetwork

volumes:
  db-data:
  pgadmin-data:
  keycloak-data:

networks:
  mynetwork:
    driver: bridge

